[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m venv venv",
  ". venv/bin/activate && pip install --upgrade pip setuptools wheel",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = ". venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"

